sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t dkaskgkdua/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true dkaskgkdua/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success2233"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-321088962883"
  bucket_path: "elasticbeanstalk-ap-northeast-2-321088962883"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY